AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: "imagenet"   # 改为字符串 "imagenet"，PyTorch 会加载 ResNet18_Weights.IMAGENET1K_V1
LEARNING_RATE: 0.01
